apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellojenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellojenkins
  template:
    metadata:
      labels:
        app: hellojenkins
    spec:
      containers:
        - name: hellojenkins
          image: ipaye/hellojenkins:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: hellojenkins-service
spec:
  selector:
    app: hellojenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
